### ISSUE TITLE
Rendered css 'link' tag isn't closed

### ISSUE THREAD

**Issue by drobar** [JimBobSquarePants/Cruncher#23]
I've got the following in my template to render the css:
`@CruncherBundler.RenderCSS("/css/www.css", "/css/ezsearch.css")` 

Which generates the following tag to the website visitor:
`<link rel="stylesheet" href="/assets-cruncher/971476941.css" >`

The `<link>` tag should be self-closed with `<link .... />` so that it validates properly.

cheers, 
 doug.

**Comment by JimBobSquarePants** [comment]
Hi Doug,

Thanks for that; not sure how I missed it. :+1: 

I'll update and get a release out asap. :smile:

**Comment by drobar** [comment]
:)

**Comment by JimBobSquarePants** [comment]
Fixed in dev just now.

**Comment by JimBobSquarePants** [comment]
Fixed in v3.1.0
https://www.nuget.org/packages/Cruncher/
