### ISSUE TITLE
Large memory use and very slow app_pool startup with Cruncher enabled

### ISSUE THREAD

**Issue by drobar** [JimBobSquarePants/Cruncher#24]
Hi, James,

I want to run a problem by you to see if there's anything that can be done. I was quite surprised by the results of using Cruncher on my small site. Granted, I've a half dozen css and script files to process but they are all just needing to be minimized and concatinated. No .less or anything fancy. 

In all result cases, all the dlls for cruncher's dependencies and all web.config entries are present on the site. Only three things were ever changed for these tests... the cruncher.dll may have been removed from the bin folder, the @using Cruncher line in my site's master layout/template may have been removed, and the two calls to @Cruncher.Render*() for the css and js files may have been removed, calling the previously-compiled asset files directly instead.

The IIS was then restarted (not just the app_pool) and the homepage for the site loaded. When the app pool stopped growing (usually within a minute or so) I recorded the memory value shown in TaskManager.

For reference, here are my calls:
`@CruncherBundler.RenderCSS("/css/www.css", "/css/ezsearch.css", "transmenu.css", "/css/forms.css", "/css/sifr-screen.css")`

`@CruncherBundler.RenderJavaScript("/scripts/helpers.js", "/scripts/transmenu.min.js", "/scripts/sifr.js", "/scripts/eucookie.min.js", "/scripts/jquery-2.1.1.min.js", "/scripts/jquery.validate.min.js", "/scripts/jquery.validate.unobtrusive.min.js", "/scripts/ jquery.unobtrusive-agax.min.js", "/scripts/main.js", "/App_Plugins/TeaCommerce/Assets/Scripts/tea-TeaCommerce.min.js")`

(yes, yes, I know... sIFR! It's an old site that's being rebuilt :))

Here are the results:
* 138k = no cruncher.dll, no using Cruncher, no Cruncher.Render*()
* 170k = **cruncher.dll**, no using Cruncher, no @Cruncher.Render*()
* 170k = cruncher.dll, **using Cruncher**, no Cruncher.Render*()
* 342k = cruncher.dll, using Cruncher, **Cruncher.Render*()**

As you can see, calling the .Render*() calls adds a ton of overhead to the app_pool. It also massively slows down the app_pool recycle time.

**Comment by JimBobSquarePants** [comment]
Hi Doug,

I *think* it's the default JavaScript engine - Jint. I had noticed it seemed to be slow when using that. It's the default though as I needed something that I didn't have to potentially jump through hoops to get working with Azure which we were using at work and I had a short timescale to work within. 

Could you do me a favour and run the same tests this time using the following engine? I saw much better recycling performance with it.

https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8

Cheers

James

**Comment by JimBobSquarePants** [comment]
I'm changing the default JavaScript engine to use the MSIE one. That has dramatically reduced both memory and load in my tests.

**Comment by JimBobSquarePants** [comment]
Fixed with v3.1.0

https://www.nuget.org/packages/Cruncher/
