### ISSUE TITLE
Could not load file or assembly LibSass.x64.DLL or one of its dependencies

### ISSUE THREAD

**Issue by BarryFogarty** [JimBobSquarePants/Cruncher#28]
Hey James

Is this compatible with Umbraco 7.3?  I tried it on a fresh nuget install of 7.3 but I got the above error.  Its a 64 bit system and the site running on IIS 8.5 (Windows 8.1).  The full YSOD I am getting at runtime is:

Could not load file or assembly 'LibSass.x64.DLL' or one of its dependencies. The specified module could not be found.

LibSass.x64.DLL is in /bin.  I tried using the DependencyWalker tool and although it reported a few issues, nothing obviously missing.

**Comment by JimBobSquarePants** [comment]
It should be though I haven't had the chance to try.

The file should get extracted to the ASP temp folder for the web application. Could you check if it is please.

**Comment by BluefinDigital** [comment]
I can confirm the LibSass.x64.DLL is in the temporary asp.net files.

I have since downgraded to Cruncher 2.1 which works fine (I don't need a
SASS compiler) - hopefully you can generate the error with the above info
though.  I figure its a missing/wrong version GAC dependency that's not a
part of my Windows/IIS.

Kind Regards,
Barry Fogarty
*m: *07590 385 063
*skype:  *barryfogarty
www.barryfogarty.com
<http://www.barryfogarty.com/?utm_source=pitch&utm_medium=email&utm_campaign=sig-gmail>

**Comment by JimBobSquarePants** [comment]
Ah.... I think I know what your issue is. 

One of my dependencies requires [Visual C++ Redistributable](http://www.microsoft.com/en-us/download/details.aspx?id=40784)

Once you install that you should be good to go.

**Comment by BarryFogarty** [comment]
NB I have revisted this for another project - and even with the C++ libraries installed I still have the issue.  I don't need Sass compilation on this project so I just removed the offending package / DLLs and all is working.

**Comment by BarryFogarty** [comment]
BTW Just noticed a warning in my project build that may explain these issues too:  Warning  There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "libsassnet, Version=1.0.0.0, Culture=neutral, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

Just to clarfiy I have now removed libsass so its not a problem on this particular project, just thought it might useful to report.

**Comment by JimBobSquarePants** [comment]
Hmmm... Could you raise the issue on the libsassnet issue tracker. 

https://github.com/darrenkopp/libsass-net

I'm just consuming his library.

**Comment by BarryFogarty** [comment]
https://github.com/darrenkopp/libsass-net/issues/39

**Comment by JimBobSquarePants** [comment]
Cheers chum!
